### ISSUE TITLE
Async Stuck

### ISSUE THREAD

**Issue by pcruse3** [Meabed/asynchronous-soap#5]
Hi,

I am running your code and it get stuck. It will literally run forever:

```
while ($active && $mrc == CURLM_OK) {
            if (curl_multi_select($mh) != -1) {
                do {
                    $mrc = curl_multi_exec($mh, $active);
                } while ($mrc == CURLM_CALL_MULTI_PERFORM);
            }
        }
```
I can see this through my xdebug_break();

Here is how I am trying to use:
```
public function otaAirAvailRq(){
        $otaAirAvailRq  = [];
        $SabreSoap      = new \SoapClientAsync(__DIR__.'/SabreXML/OTA_AirAvailLLS2.1.1RQ.wsdl', ['trace' => 1]);
        $SabreSoap->__setSoapheaders($this->_setSabreHeaders('OTA_AirAvailLLSRQ', 'OTA_AirAvailLLSRQ', false));
        foreach ($this->Itinerary->getLegs() as $leg){
            $requestIds[] = $SabreSoap->OTA_AirAvailRQ($this->_buildAvailRequest($leg, '2.1.1'));
        }
  //this is where it gets stuck in an endless loop.
      foreach ($SabreSoap->run($requestIds) as $response){
     $otaAirAvailRq[] = $response->Return;
     }
        return $otaAirAvailRq;
    }//end of otaAirPriceLlSrq
```
`curl_multi_select($mh) != -1` is always -1.. and there is nothing to change it. Seems like this is a logic error on the client. Its in a endless loop

**Comment by Meabed** [comment]
Hi @pcruse3 
The package still working and i am using it in my projects when i need it.

Could you try like this 
$responses = $SabreSoap->run($requestIds);
foreach ($responses as $response){
     var_dump($response);
 }

**Comment by pcruse3** [comment]
hi I tried that...

The issue isn't the for loop... the issue is the endless loop that takes down the server.

I never even get to that loop...

**Comment by Meabed** [comment]
I never run into this issues, 
Have a look here http://php.net/manual/en/function.curl-multi-exec.php

What version of php are you running ?

**Comment by pcruse3** [comment]
5.6.9

on Ubuntu 14.04.2.

**Comment by pcruse3** [comment]
This happens when I call `$SabreClient->run()`

**Comment by Meabed** [comment]
I see, i have only tested on php5, I will have a look. if its easy for you to switch php versions and try again? or can you run the example on ur php version.

**Comment by pcruse3** [comment]
No I can't downgrade my PHP easily.

Can you upgrade this client to use 5.6.9?

The offer to buy you a cup of coffee still stands...

**Comment by Meabed** [comment]
:) sure i will test it asap and let you know.

**Comment by Meabed** [comment]
Can you give me the soap service you trying ? 
is it only one command of the service or everything ?

**Comment by pcruse3** [comment]
There is only one command in the per file, but we run the command twice.

Unfortunately, I can't give you the soap via github... want me to email it?

**Comment by Meabed** [comment]
Sure could you email me, I think I have a solution but just to confirm email me :)

**Comment by pcruse3** [comment]
Just did…


thanks,

Paul Cruse III | pcruse3@optionsaway.com <mailto:pcruse3@optionsaway.com>
Software Engineer, Development

**Comment by Meabed** [comment]
Could you try now?
